/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef ANDROID
#include <jni.h>

/* Header for class com_xqlgame_qssz_MP3Encode */

#ifndef _Included_org_cocos2dx_javascript__MP3Encode
#define _Included_org_cocos2dx_javascript__MP3Encode
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_xqlgame_qssz_MP3Encode
 * Method:    init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_javascript_MP3Encode_init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_xqlgame_qssz_MP3Encode
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_javascript_MP3Encode_destroy
  (JNIEnv *, jclass);

/*
 * Class:     com_xqlgame_qssz_MP3Encode
 * Method:    encode
 * Signature: ([SI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cocos2dx_javascript_MP3Encode_encode
  (JNIEnv *, jclass, jshortArray, jint);



#ifdef __cplusplus
}
#endif
#endif

#endif //ANDROID
